name: Manual deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        required: true
        type: choice
        options:
          - dev
          - demo
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/quality-assurance

  deploy:
    needs: quality
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/infra-deploy
        with:
          environment: ${{ github.event.inputs.environment }}
